/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 23 Jun, 2022, 8:17:10 PM
 */

package calculator1;

import com.sun.xml.internal.bind.v2.schemagen.xmlschema.Import;
import java.awt.Image;


/**
 *
 * @author my pc
 */
public class Home extends javax.swing.JFrame {

    @Override
    public boolean imageUpdate(Image img, int infoflags, int x, int y, int w, int h) {
        return super.imageUpdate(img, infoflags, x, y, w, h);
    }

    /** Creates new form Home */
    
    public Home() {
        initComponents();


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zerobutton = new javax.swing.JButton();
        starButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixbutton = new javax.swing.JButton();
        minuButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        screenTextField = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        ninebutton = new javax.swing.JButton();
        eighgtButton = new javax.swing.JButton();
        sevenbutton = new javax.swing.JButton();
        secondTextField = new javax.swing.JTextField();
        dotButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        modButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calculator\n");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(java.awt.Color.black);
        setIconImages(null);

        zerobutton.setBackground(new java.awt.Color(0, 0, 0));
        zerobutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        zerobutton.setForeground(new java.awt.Color(255, 255, 255));
        zerobutton.setText("0");
        zerobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zerobuttonMouseClicked(evt);
            }
        });
        zerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobuttonActionPerformed(evt);
            }
        });

        starButton.setBackground(new java.awt.Color(0, 0, 0));
        starButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        starButton.setForeground(new java.awt.Color(255, 255, 255));
        starButton.setText("*");
        starButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                starButtonMouseClicked(evt);
            }
        });

        divideButton.setBackground(new java.awt.Color(0, 0, 0));
        divideButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        divideButton.setForeground(new java.awt.Color(255, 255, 255));
        divideButton.setText("/");
        divideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideButtonMouseClicked(evt);
            }
        });

        equalButton.setBackground(new java.awt.Color(255, 102, 0));
        equalButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        equalButton.setText("=");
        equalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalButtonMouseClicked(evt);
            }
        });

        oneButton.setBackground(new java.awt.Color(0, 0, 0));
        oneButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        oneButton.setForeground(new java.awt.Color(255, 255, 255));
        oneButton.setText("1");
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneButtonMouseClicked(evt);
            }
        });

        twoButton.setBackground(new java.awt.Color(0, 0, 0));
        twoButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        twoButton.setForeground(new java.awt.Color(255, 255, 255));
        twoButton.setText("2");
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoButtonMouseClicked(evt);
            }
        });

        threeButton.setBackground(new java.awt.Color(0, 0, 0));
        threeButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        threeButton.setForeground(new java.awt.Color(255, 255, 255));
        threeButton.setText("3");
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeButtonMouseClicked(evt);
            }
        });

        fourButton.setBackground(new java.awt.Color(0, 0, 0));
        fourButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        fourButton.setForeground(new java.awt.Color(255, 255, 255));
        fourButton.setText("4");
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourButtonMouseClicked(evt);
            }
        });

        fiveButton.setBackground(new java.awt.Color(0, 0, 0));
        fiveButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        fiveButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveButton.setText("5");
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveButtonMouseClicked(evt);
            }
        });

        sixbutton.setBackground(new java.awt.Color(0, 0, 0));
        sixbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        sixbutton.setForeground(new java.awt.Color(255, 255, 255));
        sixbutton.setText("6");
        sixbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixbuttonMouseClicked(evt);
            }
        });

        minuButton.setBackground(new java.awt.Color(0, 0, 0));
        minuButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        minuButton.setForeground(new java.awt.Color(255, 255, 255));
        minuButton.setText("-");
        minuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minuButtonMouseClicked(evt);
            }
        });

        plusButton.setBackground(new java.awt.Color(0, 0, 0));
        plusButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        plusButton.setForeground(new java.awt.Color(255, 255, 255));
        plusButton.setText("+");
        plusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plusButtonMouseClicked(evt);
            }
        });

        screenTextField.setForeground(new java.awt.Color(255, 0, 0));
        screenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenTextFieldActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(255, 102, 0));
        backbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 8)); // NOI18N
        backbutton.setText("AC");
        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        ninebutton.setBackground(new java.awt.Color(0, 0, 0));
        ninebutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        ninebutton.setForeground(new java.awt.Color(255, 255, 255));
        ninebutton.setText("9");
        ninebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ninebuttonMouseClicked(evt);
            }
        });

        eighgtButton.setBackground(new java.awt.Color(0, 0, 0));
        eighgtButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        eighgtButton.setForeground(new java.awt.Color(255, 255, 255));
        eighgtButton.setText("8");
        eighgtButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eighgtButtonMouseClicked(evt);
            }
        });

        sevenbutton.setBackground(new java.awt.Color(0, 0, 0));
        sevenbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18));
        sevenbutton.setForeground(new java.awt.Color(255, 255, 255));
        sevenbutton.setText("7");
        sevenbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenbuttonMouseClicked(evt);
            }
        });
        sevenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbuttonActionPerformed(evt);
            }
        });

        secondTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondTextFieldActionPerformed(evt);
            }
        });

        dotButton.setBackground(new java.awt.Color(0, 0, 0));
        dotButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24));
        dotButton.setForeground(new java.awt.Color(255, 255, 255));
        dotButton.setText(".");
        dotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dotButtonMouseClicked(evt);
            }
        });
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 102, 0));
        backButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        backButton.setText("<");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        modButton.setBackground(new java.awt.Color(0, 0, 0));
        modButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 10));
        modButton.setForeground(new java.awt.Color(255, 255, 255));
        modButton.setText("%");
        modButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modButtonMouseClicked(evt);
            }
        });
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(screenTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dotButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(oneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(sevenbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(secondTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zerobutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(twoButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(threeButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(eighgtButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ninebutton)
                                            .addComponent(sixbutton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(starButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(plusButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(minuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(divideButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eighgtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sevenbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ninebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(sixbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(twoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(threeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(starButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dotButton)
                        .addComponent(zerobutton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void screenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_screenTextFieldActionPerformed

    private void sevenbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenbuttonMouseClicked
        // TODO add your handling code here:
        if(screenTextField.getText().equals("")){
                screenTextField.setText("7");
          }else{
            screenTextField.setText(screenTextField.getText()+"7");
          }
          secondTextField.setText(secondTextField.getText()+"7");
    }//GEN-LAST:event_sevenbuttonMouseClicked

    private void eighgtButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eighgtButtonMouseClicked
       // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
                screenTextField.setText("8");
          }else{
            screenTextField.setText(screenTextField.getText()+"8");
         }
          secondTextField.setText(secondTextField.getText()+"8");
    }//GEN-LAST:event_eighgtButtonMouseClicked

    private void ninebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ninebuttonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
               screenTextField.setText("9");
        }else{
               screenTextField.setText(screenTextField.getText()+"9");
        }
          secondTextField.setText(secondTextField.getText()+"9");
    }//GEN-LAST:event_ninebuttonMouseClicked

    private void fourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
               screenTextField.setText("4");
        }else{
               screenTextField.setText(screenTextField.getText()+"4");
        }
           secondTextField.setText(secondTextField.getText()+"4");
    }//GEN-LAST:event_fourButtonMouseClicked

    private void fiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
                 screenTextField.setText("5");
        }else{
                  screenTextField.setText(screenTextField.getText()+"5");
        }
          secondTextField.setText(secondTextField.getText()+"5");
    }//GEN-LAST:event_fiveButtonMouseClicked

    private void sixbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixbuttonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
                 screenTextField.setText("6");
        }else{
                 screenTextField.setText(screenTextField.getText()+"6");
        }
          secondTextField.setText(secondTextField.getText()+"6");
    }//GEN-LAST:event_sixbuttonMouseClicked

    private void oneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){
               screenTextField.setText("1");
        }else{
              screenTextField.setText(screenTextField.getText()+"1");            
        }
          secondTextField.setText(secondTextField.getText()+"1");
    }//GEN-LAST:event_oneButtonMouseClicked

    private void twoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){

            screenTextField.setText("2");
            
        }else{
            screenTextField.setText(screenTextField.getText()+"2");
            
        }
          secondTextField.setText(secondTextField.getText()+"2");
    }//GEN-LAST:event_twoButtonMouseClicked

    private void threeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){

            screenTextField.setText("3");
             
        }else{
            screenTextField.setText(screenTextField.getText()+"3");
           
        }
          secondTextField.setText(secondTextField.getText()+"3");
    }//GEN-LAST:event_threeButtonMouseClicked

    private void zerobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zerobuttonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){

            screenTextField.setText("0");
             
        }else{
            screenTextField.setText(screenTextField.getText()+"0");
            
        }
          secondTextField.setText(secondTextField.getText()+"0");
    }//GEN-LAST:event_zerobuttonMouseClicked
    String oldValue;
    String action=null;
    private void starButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_starButtonMouseClicked
        // TODO add your handling code here:
   
         if(action==null){
       oldValue=  screenTextField.getText();
      screenTextField.setText("");
      action="mult";
       secondTextField.setText(secondTextField.getText()+"*");
        }else{
            cal();
            oldValue=Float.toString(result);
             action="mult";
             screenTextField.setText("");
              secondTextField.setText(secondTextField.getText()+"*");

        }
       

    }//GEN-LAST:event_starButtonMouseClicked
    String newValue;
    float result;
  
    private void equalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalButtonMouseClicked
        // TODO add your handling code here:
       
  
       cal();

      screenTextField.setText(result+"");
      
      secondTextField.setText(secondTextField.getText()+"=");
      secondTextField.setText(secondTextField.getText()+result+"");
      
        action=null;

    }//GEN-LAST:event_equalButtonMouseClicked
   
    private void divideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideButtonMouseClicked
        // TODO add your handling code here:
  
         if(action==null){
       oldValue=  screenTextField.getText();
      screenTextField.setText("");
      action="div";
       secondTextField.setText(secondTextField.getText()+"/");
        }else{
            cal();
           oldValue=Float.toString(result);
             action="div";
             screenTextField.setText("");
              secondTextField.setText(secondTextField.getText()+"/");

        }
           
    }//GEN-LAST:event_divideButtonMouseClicked

    private void minuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minuButtonMouseClicked
        // TODO add your handling code here:
   
         if(action==null){
       oldValue=  screenTextField.getText();
      screenTextField.setText("");
      action="minus";
       secondTextField.setText(secondTextField.getText()+"-");
        }else{
            cal();
            oldValue=Float.toString(result);
             action="minus";
             screenTextField.setText("");
              secondTextField.setText(secondTextField.getText()+"-");

        }
           
    }//GEN-LAST:event_minuButtonMouseClicked

    private void plusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusButtonMouseClicked
        // TODO add your handling code here:
       
        if(action==null){
       oldValue=  screenTextField.getText();
      screenTextField.setText("");
      action="plus";
      secondTextField.setText(secondTextField.getText()+"+");

        }else{
            cal();
             oldValue=Float.toString(result);
             action="plus";
             screenTextField.setText("");
              secondTextField.setText(secondTextField.getText()+"+");

        }
      
    }//GEN-LAST:event_plusButtonMouseClicked

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        screenTextField.setText("");
        secondTextField.setText("");
         
          action=null;
    }//GEN-LAST:event_backbuttonMouseClicked

    private void secondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondTextFieldActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonActionPerformed

    private void zerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zerobuttonActionPerformed

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modButtonActionPerformed

    private void sevenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenbuttonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void dotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotButtonMouseClicked
        // TODO add your handling code here:
         if(screenTextField.getText().equals("")){

            screenTextField.setText(".");

        }else{
            screenTextField.setText(screenTextField.getText()+".");

        }
          secondTextField.setText(secondTextField.getText()+".");

    }//GEN-LAST:event_dotButtonMouseClicked

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotButtonActionPerformed

    private void modButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modButtonMouseClicked
        // TODO add your handling code here:
         if(action==null){
       oldValue=  screenTextField.getText();
      screenTextField.setText("");
      action="mod";
      secondTextField.setText(secondTextField.getText()+"%");

        }else{
            cal();
            oldValue=Float.toString(result);
             action="mod";
             screenTextField.setText("");
              secondTextField.setText(secondTextField.getText()+"%");

        }

    }//GEN-LAST:event_modButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
     
        screenTextField.setText(screenTextField.getText().substring(0,screenTextField.getText().length()-1));
        secondTextField.setText(secondTextField.getText().substring(0,secondTextField.getText().length()-1));
        
        

    }//GEN-LAST:event_backButtonMouseClicked
 private void cal(){

        newValue= screenTextField.getText();
      float old=Float.parseFloat(oldValue);
      float newv=Float.parseFloat(newValue);
     if(action == null ? "plus" == null : action.equals("plus")){
         result=old+newv;
     }else if(action == null ? "minus" == null : action.equals("minus")){
         result=old-newv;
     }else if(action == null ? "div" == null : action.equals("div")){
         result=old/newv;
     }else if (action == null ? "mult" == null : action.equals("mult")){
         result=old*newv;
     }else if(action == null ? "mod" == null : action.equals("mod")){
         result=old%newv;
     }
     
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton eighgtButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton minuButton;
    private javax.swing.JButton modButton;
    private javax.swing.JButton ninebutton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JTextField screenTextField;
    private javax.swing.JTextField secondTextField;
    private javax.swing.JButton sevenbutton;
    private javax.swing.JButton sixbutton;
    private javax.swing.JButton starButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zerobutton;
    // End of variables declaration//GEN-END:variables


}
